### PR TITLE
[I18N] Greek language support updated for new strings

### PR DESCRIPTION
**Pull request by kmav**
Greek language support updated for new strings related to changing app language and more.
@RocketChat/ios

Also resolves and closes issue #1363

### CODE REVIEW

**Comment by kmav** [comment]
Also resolves and closes issue #1363 
Something went wrong and two PRs merged to one and that I had some white space violation errors...

**Comment by artrmz** [comment]
@kmav You probably did both changes on the same branch. Preferably each issue should be handled on different branch that is created from develop (which you should always sync with upstream develop)

**Comment by kmav** [comment]
This includes also the AuthViewController localization fixes and new localization strings.
I was expecting that the 1st PR has finished or that all are queued...

@rafaelks or @artrmz Could you please advise how can I resolve this? It is confusing that there where warnings for File size in lines for AuthViewController (in addition with end of line blanks)...

Also, I am not aware of this develop branch process that you have mentioned. Could you please clarify?
Thank you.

**Comment by kmav** [comment]
Appologies for confusion and any mess...
Maybe you could provide a status on this and any action plan? Do you want me to do the whole think [ a)greek lang updates, b) auth changes ] from the beginning somehow?
I dont understand what is milestone 2.1.0.
Thank you.

**Comment by rafaelks** [comment]
@kmav You PR looks fine! We just didn’t have time to review yet, hehe. Thank you!

**Comment by kmav** [comment]
@rafaelks :) Just seen your message... I have made a git surgery to my commits in order to create branches based on them, so that I can follow @artrmz advice and conform to general contribution guidelines for PRs... Before a while I have finished and created a new PR only for the initial Greek part that adds the new translations only. Hope is better now because the PR-changes are more focused to their different objectives :) :)  if you agree, I can proceed with the 2nd part that has to do with the AuthViewController localisation.

**Pull request closed without merging**
