### PR TITLE
[NEW] Support GitLab OAuth

### LINKED ISSUE #1161: [NEW] Authentication GitLab

### PR DESCRIPTION
**Pull request by cardoso**
@RocketChat/ios

There's something wrong with open's gitlab settings, so I'm waiting for it to be fixed.

Closes #1161

### CODE REVIEW

**Comment by rafaelks** [comment]
👍

**Comment by rafaelks** [comment]
Back-end is having issues with GitLab authentication: https://github.com/RocketChat/Rocket.Chat/issues/9660

**Comment by rafaelks** [comment]
@cardoso Made some changes on scope & removed one unused property. This is working and ready to review. 👍

**Comment by cardoso** [comment]
It's working for me now @rafaelks 👍 let's merge this

**Pull request merged**
