### PR TITLE
[FIX] Theming on swipe actions

### PR DESCRIPTION
**Pull request by Sameesunkaria**
@RocketChat/ios

 
 

Supports #1960

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
What do you guys think about coloring the "mark as read" button in the same color as the action icons in the header?  :)

**Comment by Sameesunkaria** [comment]
@kaiiiiiiiii (had to type this out, on mobile 🙃) Are you talking about the tint color of the buttons?

**Comment by kaiiiiiiiii** [comment]
2b399b1a-f849-4b53-b26d-66bf281c33d4
 That kind of blue :) Fits better than the light blue I think 🤔

**Comment by Sameesunkaria** [comment]
@kaiiiiiiiii

**Comment by kaiiiiiiiii** [comment]
Idk, for me it looks a lot cleaner on your last screenshots :D I mean, it's the way how WhatsApp, Outlook and Co. do it ^^' (except for the dark mode, because they've none)

**Comment by Sameesunkaria** [comment]
@kaiiiiiiiii We use a bluer blue for the rocket.chat tintColor. The default iOS tintColor looks fine to me, but the RC blue seems a bit striking to me. But, if you guys like this better, I can make the changes.

cc @rafaelks @thiagosanchz

**Comment by thiagosanchz** [comment]
Guys! Incredible feature! We'll design icons, choose colors and animation for that, we'll share with you next week.

**Comment by rafaelks** [comment]
@thiagosanchz Thank you, you rock! 👊

**Comment by thiagosanchz** [comment]
Guys, I did the components to swipe interactions, but we discuss that favorite looks more important than leave a channel for mobile application, like a Pin for other apps. I use the same icon that we use in our applications to follows the same features.  swipe

**Comment by cardoso** [comment]
@brunosquadros I think It's been done in this PR: 
https://github.com/RocketChat/Rocket.Chat.iOS/pull/1938

**Pull request merged**
