### PR TITLE
[CHORE] Optimize project to build faster in debug mode

### PR DESCRIPTION
**Pull request by artrmz**
@RocketChat/ios

Optimized project as suggested in [here](https://github.com/fastred/Optimizing-Swift-Build-Times)

Debug configuration should compile much faster now. According to my tests it's about 30%. Since tests are building using Debug configuration it should also speed up CI tests.

My test:
Before PR: 321.285s
Before PR: 330.760s

After PR: 210.469s
After PR: 235.977s
After PR: 245.996s

### CODE REVIEW

**Comment by rafaelks** [comment]
@artrmz Awesome! Thank you for the PR... I'll take a look, could also give it a try @cardoso?

**Comment by artrmz** [comment]
@rafaelks Hopefully it'll also work outside my testing environment :)

**Comment by cardoso** [comment]
Nice one @artrmz ! Approved 👍

**Comment by rafaelks** [comment]
@artrmz This one also reduced our time on CI 🎉. Thank you! 👍

**Pull request merged**
