### PR TITLE
[NEW] Emoji picker to add new reactions

### LINKED ISSUE #1080: [NEW] Support EmojiPicker to react to a message

### PR DESCRIPTION
**Pull request by cardoso**
@RocketChat/ios

|Preview|
|-|
||

Closes #1080

### CODE REVIEW

**Comment by cardoso** [comment]
Ready for review @rafaelks :)

**Comment by rafaelks** [comment]
This is looking super awesome @cardoso! Some small feedbacks before we merge it...

1. Bottom space into the section title is too small, let's increase it to ~8px; Reduce the fontSize by 50% and use a bold (or semi-bold) font; AND also let's remove the "back" button title;

screen shot 2017-12-28 at 10 18 55 pm

2. Top spacing between the reaction and ANY attachment is too small. Needs to be at least 8px;

screen shot 2017-12-28 at 10 19 28 pm

3. Top spacing on the section header is also too little; Maybe increase the spacing between sections into the collection view;

screen shot 2017-12-28 at 10 20 13 pm

**Comment by cardoso** [comment]
Ready for review again @rafaelks . 

Applied your suggestions and also added skin tone selection and frequent emojis :)

**Comment by rafaelks** [comment]
Super!!! Just a few more things.

1.  Increase the edges (top and bottom) to 8px of the collection view;

screen shot 2017-12-29 at 9 26 15 am

2. Are these numbers real emojis? I didn't find them in my iOS keyboard;

screen shot 2017-12-29 at 9 27 40 am

**Comment by cardoso** [comment]
@rafaelks these emojis are in the web picker. asterisk, hash, one, two.. etc...

Should we remove them because they don't look good in iOS?

**Comment by cardoso** [comment]
@rafaelks 

Here's a preview with the nice fontawesome.com icons:

**Comment by rafaelks** [comment]
New icons are looking great, but there are issues when using with iPhone X. See the images below (bottom of the images).

img_1225
img_1226

Also, some other things to be improved:

1. Let's add a placeholder to the search bar ("Search for an emoji");
2. Let's add a title to the screen ("Choose a reaction");

**Comment by cardoso** [comment]
Fixed the layout issues and added the placeholder and title.

**Pull request merged**
