### PR TITLE
group subscription by SubscriptionType

### PR DESCRIPTION
**Pull request by CodeBanBan**
group subscription by SubscriptionType

### CODE REVIEW

**Comment by rafaelks** [comment]
@CodeBanBan Thank you for your contribution. We're still not sure that subscription list will have the same order/group that web does today. We're thinking in order chats in other terms. I'll let this PR open until we decide it. Thank you! 🚀

**Comment by rafaelks** [comment]
@CodeBanBan Can you fix the conflicts so we can merge your PR? Thank you!

**Comment by CodeBanBan** [comment]
@rafaelks OK. I will fix conflicts.

**Comment by rafaelks** [comment]
@CodeBanBan Looking good! Merging now! Thank you! 👍 🚀

**Pull request merged**
