### PR TITLE
[NEW] Add Japanese translation file

### PR DESCRIPTION
**Pull request by YuuTakahara**
@RocketChat/ios

Add japanese translation file.

### CODE REVIEW

**Comment by rafaelks** [comment]
Looking awesome @YuuTakahara, thank you very much!

**Comment by Sameesunkaria** [comment]
@YuuTakahara Thanks a lot for the translations. 🙌🏻
There are a few new string in `develop` which are not synced with the Japanese strings file. Can you help translate those as well?

**Comment by YuuTakahara** [comment]
@rafaelks Thanks for the work.
Should I do something?
This is my first pull requuest, so there are a lot of things I do not know.

**Comment by YuuTakahara** [comment]
@Sameesunkaria I can do it.
Specifically, what file or word translation is required?
Should I add ja.lproj to Rocket.Chat.iOS/Rocket.Chat.ShareExtension/Resources/?

**Comment by Sameesunkaria** [comment]
@YuuTakahara your current changes have been merged into the codebase.

You can go through the changes I made in #2149 to the Japanese strings file, and add the translated versions of those strings in a new PR. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
