### PR TITLE
[NEW] Add user profile picture to the menu on the left

### LINKED ISSUE #480: Add user profile picture to the menu on the left
Can you please add the profile picture of a user to the left menu just beside the username? :-)

I created a little preview:

image

Looks awesome right? 👍

### PR DESCRIPTION
**Pull request by micheltlutz**
@RocketChat/ios

Closes #480

Profile photo added successfully

21198444_1775010962527809_460053435_o

### CODE REVIEW

**Comment by rafaelks** [comment]
@micheltlutz This PR also changes the left-side menu color and text color, right?

**Comment by micheltlutz** [comment]
@rafaelks Yes  I Change the color like a new colors on web application.

**Comment by rafaelks** [comment]
@micheltlutz OK, great! Can you add the email you used in your first commit to your GitHub account and let me know? The CLA isn't passing because it seems you used two different accounts.

**Comment by rafaelks** [comment]
Looking great, thank you @micheltlutz!

**Pull request merged**
