### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### RocketChat/Rocket.Chat.iOS now has a Chat Room on Gitter

@gsaslis has just created a chat room. You can visit it here: [https://gitter.im/RocketChat/Rocket.Chat.iOS](https://gitter.im/RocketChat/Rocket.Chat.iOS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/RocketChat/Rocket.Chat.iOS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by sampaiodiego** [comment]
is there a real intention of using gitter?

**Comment by graywolf336** [comment]
Yeah I think discussion should be happening on the Rocket.Chat's demo/community...

**Comment by engelgabriel** [comment]
@gsaslis, please crete a channel at https://demo.rocket.chat and remove the Gitter link.

**Comment by gsaslis** [comment]
:) fair enough!  

i just saw some of you guys already on there and that the app already had permission for the organization, so I thought it's a standard thing you're using and that I wasn't aware of...

**Comment by engelgabriel** [comment]
We used all other competitors as tests, so we have benchmarks :)

But the demo (soon to be called COMMUNITY server) is always the official channel.

**Pull request merged**
