### PR TITLE
[NEW] Support self signed certificates for Client SSL

### LINKED ISSUE #708: [NEW] Support self-signed certificates for SSL (WebSocket & REST)
- Your Rocket.Chat app version: 1.4.0 (96)
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: iPad Mini 4 on 11.0

Hi all, we have a reverse proxy in front of our RocketChat for employees to access from the outside securely.  It requires a client SSL certificate.  This was a non-issue on regular computers; just requires some generating of CSRs and we sign them internally, push back the resulting cert.

On the iOS side, we've run into an issue where only Safari seems to be able to connect to our certificate-based proxy server, so the RocketChat app doesn't work externally.  The steps that have been taken were to generate a key and cert on the server side since iOS doesn't have that functionality.  Turn the resulting cert and key into a PKCS#12 (.p12) format file.  Get the file over to the iOS device, click it, tell it to install.  Once that is done, the certificate is visible under Settings -> General -> Profile.  If you fire up Safari iOS and hit our RocketChat external URL, it prompts to use the cert, then RocketChat works great.  RocketChat+ App does not prompt and just says can't connect.

I don't know the internal workings of the app and how it makes its requests, but wanted to bring this up in case there's any chance of modifying it in a way that would either front-end Safari in some hidden way, or perhaps make use of additional iOS functions that would allow it to gain access to the 'Profile' certificates.  Or perhaps Apple has locked that away and such a setup would be impossible.

### PR DESCRIPTION
**Pull request by atc07**
@RocketChat/ios

The changes for the issue are in commit "17b1d0e". Client Authentication certificate functionality: 1) Share extension to load a certificate from attachment in email. 2) Password client authentication certificate popup and loading. 

We also had to make changes to the Starscream library in order for this to work.

Closes #708

### CODE REVIEW

**Comment by cardoso** [comment]
Hi @atc07 . Thanks for your contribution!

Before we proceed with reviewing, could you sign the CLA and look into the lint issues?

**Comment by atc07** [comment]
@cardoso It's weird - I signed it and when I go to the link it says it is signed: https://screencast.com/t/A9A7DbAt

We will look into the Lint issues and respond again after we update.

**Comment by cardoso** [comment]
Looks like @jarrillaga is the author of the commits, so he needs to sign the CLA :)

**Comment by jarrillaga** [comment]
Hi @cardoso, first of all, thanks for RocketChat+ :) 

What about the CircleCI test that failed? There are a lot of lint warnings in the Starscream library, we needed to modify it in order that the sockets communication know about the client authentication certificate and we had to include it in the project (we deleted the pod).

**Comment by cardoso** [comment]
@jarrillaga the lint tests failed because the code is not conforming to our style guides.

You can see above the comments @houndci-bot made on your code. It's likely that if you fix them, the tests will succeed.

Thanks!

**Comment by rafaelks** [comment]
Closing this one for now.

**Pull request closed without merging**
