### PR TITLE
[I18N] Update greek translations for 3.0.0

### PR DESCRIPTION
**Pull request by kmav**
@RocketChat/ios
@Sameesunkaria @rafaelks 

e-mail/email word cannot be translated in greek without creating a string of 20-30 characters :)
It is ok like that.

### CODE REVIEW

**Comment by Sameesunkaria** [comment]
@kmav Thank you very much! There are some strings for the share extension as well.

**Comment by kmav** [comment]
Share extension? OK. I will check later. 
Should I use this same greek-20180714 again and resubmit new pull request?

**Comment by Sameesunkaria** [comment]
@kmav You have push those commits to this PR.

**Comment by kmav** [comment]
Is ti OK now?

**Comment by rafaelks** [comment]
Thank you very much @kmav!!! 👊

**Pull request merged**
