### PR TITLE
[FIX] iOS client certificate-based access

### LINKED ISSUE #708: [NEW] Support self-signed certificates for SSL (WebSocket & REST)
- Your Rocket.Chat app version: 1.4.0 (96)
- Your Rocket.Chat server version: 0.58.2
- Device (or Simulator) you're running with: iPad Mini 4 on 11.0

Hi all, we have a reverse proxy in front of our RocketChat for employees to access from the outside securely.  It requires a client SSL certificate.  This was a non-issue on regular computers; just requires some generating of CSRs and we sign them internally, push back the resulting cert.

On the iOS side, we've run into an issue where only Safari seems to be able to connect to our certificate-based proxy server, so the RocketChat app doesn't work externally.  The steps that have been taken were to generate a key and cert on the server side since iOS doesn't have that functionality.  Turn the resulting cert and key into a PKCS#12 (.p12) format file.  Get the file over to the iOS device, click it, tell it to install.  Once that is done, the certificate is visible under Settings -> General -> Profile.  If you fire up Safari iOS and hit our RocketChat external URL, it prompts to use the cert, then RocketChat works great.  RocketChat+ App does not prompt and just says can't connect.

I don't know the internal workings of the app and how it makes its requests, but wanted to bring this up in case there's any chance of modifying it in a way that would either front-end Safari in some hidden way, or perhaps make use of additional iOS functions that would allow it to gain access to the 'Profile' certificates.  Or perhaps Apple has locked that away and such a setup would be impossible.

### PR DESCRIPTION
**Pull request by xingchen966**
@RocketChat/ios

Closes #708

Dependency library has also been modified.
"SscContextIn" and "sslContextOut" in "WebSocket.swift" in the "Starscream" library need to be submitted to the client certificate.

### CODE REVIEW

**Comment by rafaelks** [comment]
@xingchen966 Thanks for your PR... I see that there's a lot of Swift issues with our `swiftlint`. Could you fix those, please?

**Comment by rafaelks** [comment]
Closing this one due to inactivity & conflicts.

**Comment by jarrillaga** [comment]
Hi @xingchen966, how are you?  I need your help, do you solve to make this work? I have dowload your code changes but I´m facing a lot of issues. Do you have your source code working? Thanks dude.

**Comment by jarrillaga** [comment]
Hey Guys ! Someone manage to make it work ? Please I really need the fix in Starscream in order to manage the client certificate authentication? @xingchen966

**Comment by omar-saadoun** [comment]
We also need that!!! Anyone that has solved this? Thanks in advance!

**Comment by rafaelks** [comment]
@jarrillaga @omar-saadoun In the meantime, if you guys don't find a way to use the self-signed certificate, you can also allow insecure connections in your apps. We don't recommend it, but if that's the case for you guys, you can take a look on the following links:

- https://stackoverflow.com/a/40299837/1088230
- https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

We do plan to have a better documentation/support for self-signed certificates in the future.

**Comment by xingchen966** [comment]
@jarrillaga @omar-saadoun @rafaelks 
Hello friends, I am a Java developer, not very skilled in swift. For swiftlint problem, I can not solve it. The code submitted here for solving self-signed certificates does work well. Here I have the code submitted to everyone, including Starscream project code. I hope everyone can be rebuilt into a common version submitted to provide for everyone to use. Thank you very much.
Starscream project submission code see:
https://github.com/daltoniam/Starscream/issues/436#issuecomment-357763756

**Pull request closed without merging**
