### PR TITLE
[I18N] Add Greek Localization

### LINKED ISSUE #1350: [I18N] Support Greek language
Do you want or plan to support Greek in native iOS app? Do you want translation? I could maybe do the translation and proceed to a pull request. 
In the case that you like the idea, could you please advise if I should first fork the repo. For the moment I just followed your instructions and did a git clone.
Best regards,
Konstantinos

### PR DESCRIPTION
**Pull request by kmav**
@RocketChat/ios

Closes #1350 

Added Greek support in RCEmojiKit.strings, Localizable.strings, VoiceOver.strings Greek files.

BR,
Konstantinos

### CODE REVIEW

**Comment by rafaelks** [comment]
Amazing @kmav! You did it!!! 👏

**Comment by kmav** [comment]
Thank hou @rafaelks. I am very glad!
I just wonder what is that "x" for Codecov. I thought that it failed...
Also, if I want to cntribute futher, how I can run the app in my simulator or device, or is it not necessary??

BTW, I see that in on of the first quthorization Controllers, there is no Localization in strings shown there. Maybe I can create another issue and proceed for a fix...

**Comment by rafaelks** [comment]
@kmav Hehe, Codecov is crazy sometimes.

1. If you only want to contribute with strings, it's not necessary to run the application; We can do that for you.
2. Can you point me what fine & line are you talking about?

**Comment by rafaelks** [comment]
@kmav Good catch! Yes, we would have to create an IBOutlet from this labels to the code. Can you do that for us?

**Comment by kmav** [comment]
I am opening a new issue for that just to be documented.

**Pull request merged**
