### PR TITLE
[IMPROVEMENT] Make users searching in create new room (inviting user) case and diacritic insensitive

### LINKED ISSUE #1330: [Bug] Inviting users case sensitive
- Your Rocket.Chat app version: 2.0.2
- Your Rocket.Chat server version: 0.61.1
- Device (or Simulator) you're running with: SE

When creating a new channel, the selection for users is case sensitive.
How to test: 
- Create user Matheus (with upercase M)
- Create a new channel and add a user , starting with a lowercase "m"

=> You won't find it

### PR DESCRIPTION
**Pull request by artrmz**
@RocketChat/ios

Closes #1330

### CODE REVIEW

**Comment by Hrayr2112** [comment]
I guess you should use CONTAINS[cd] instead of CONTAINS[c]

**Comment by artrmz** [comment]
Can add that if we want to be diacritic-insensitive as well?

**Comment by Hrayr2112** [comment]
Ok, thanks)

**Comment by Hrayr2112** [comment]
As I know its okay

**Comment by rafaelks** [comment]
@artrmz Thank you!!! 👊

**Pull request merged**
