### PR TITLE
[FIX] Owner user is not able to send message on a public readonly channel (issue #2003)

### LINKED ISSUE #2003: [INVESTIGATE][BUG] Owner user is not able to send messages on a public readonly channel (iOS version only)
**Environment:**
Rocket.Chat app version: 3.0.0 (197)
Rocket.Chat server version: 0.66.3
Device (or Simulator) you're running with: iPhone 7 (IOS 11.4)

**Pre-condition:**
Created public readonly channel.
User has been unmuted on a Broadcast channel through the web app.
User is already login on the mobile app.
User has been set as a channel owner.

**Steps:**

Go to the created public readonly channel.
Verify sending message
**Expected Result:**
User on the public readonly channel should be allowed to send messages to the channel.

**Actual Result:**
QA FAILED. User was not allowed to send messages.

In Android and Web version the user is allowed to write message.

**Please see attached photos:**
rocketchatiphonescreen
rocketchatweb

### PR DESCRIPTION
**Pull request by sdriton**
@RocketChat/ios

Resolves #2003

### CODE REVIEW

**Comment by sdriton** [comment]
@rafaelks Can you review my PR?

**Comment by cardoso** [comment]
Nice catch @sdriton !

**Comment by rafaelks** [comment]
@sdriton Thanks for the PR, good finding! :)

**Comment by sdriton** [comment]
Thanks @cardoso @rafaelks

**Pull request merged**
