### PR TITLE
[NEW] Making Background Color Uniform When Message is Swiped

### LINKED ISSUE #2230: [IMPROVEMENT] Swipe to read message appear different background
When I swipe a message to right to make message read or unread, another background (grey) appear. We can set this background with blue too. 
img_47b1e7ac7473-1

### PR DESCRIPTION
**Pull request by SIMRAN1**
@RocketChat/ios

Closes #2230 
Making the background color uniform.
simulator screen shot - iphone 8 plus - 2018-11-24 at 17 43 43

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@rafaelks please review the PR!

**Comment by Sameesunkaria** [comment]
@SIMRAN1 Thank you for your efforts! 🎉
Changing from `.selection` to `.none` would disable the selection of mark read/unread on a longer swipe. We were hoping to keep the longer swipe interactions.

**Comment by SIMRAN1** [comment]
@Sameesunkaria I will update the PR accordingly!

**Comment by rafaelks** [comment]
Will close the PR until we have a definitive solution for this. 👍

**Pull request closed without merging**
