### PR TITLE
Portuguese (PT) translation

### PR DESCRIPTION
**Pull request by TheMythPT**
@RocketChat/ios

Not sure if it's needed but i suppose so.

So, here it is.

### CODE REVIEW

**Comment by soundstorm** [comment]
You could have just pushed into your other PR branch :)

**Comment by TheMythPT** [comment]
well, I could (but I'm not used to use GitHub to make PR's). xD

**Comment by Sameesunkaria** [comment]
@TheMythPT Haha, I see the `First-time contributor` badge. Congratulations! 🎉 and thanks a lot!

**Comment by soundstorm** [comment]
@TheMythPT pushing into the branch of your PR will also update the PR :)

**Comment by TheMythPT** [comment]
@Sameesunkaria, yeah, it's my 1st contribution to iOS (although I'm an Android user).
You can blame @rafaelks for that!
He still owes me a `caipirinha`!
:grimacing:

**Comment by TheMythPT** [comment]
@soundstorm I'll take that advice in account next time, I promise! 
:grin:

**Comment by rafaelks** [comment]
@TheMythPT Thanks a lot! 🍸

**Pull request merged**
