### PR TITLE
[NEW] Making set current room func

### LINKED ISSUE #1339: [NEW] Improve the ways the app receives push notification
I want to receive push notification when I am online, too.
If I am talking in Channel A and User A sends message to me in Direct ChatRoom, I want to receive push notification of it.
So I made some changes on server side, too.
I need to receive current room id from mobile app.

### PR DESCRIPTION
**Pull request by ggrish**
@RocketChat/ios

Closes #1339

### CODE REVIEW

**Comment by rafaelks** [comment]
@ggrish Can you explain what this change does?

**Comment by ggrish** [comment]
Hi @rafaelks

This is for send push notification of user not opened room.
so in mobile, need to inform current room id.
it is sending current opened room id by using method.

thanks

**Comment by rafaelks** [comment]
@ggrish Is this method already merged in our back-end?

**Comment by ggrish** [comment]
@rafaelks I pushed all code already.
I think it may be included in next version.

**Comment by rafaelks** [comment]
@ggrish What's the PR?

**Comment by ggrish** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/9887

**Comment by rafaelks** [comment]
@ggrish I'll close the PR for now, if https://github.com/RocketChat/Rocket.Chat/pull/9887 gets merged we open it again. Thank you!

**Pull request closed without merging**
