### PR TITLE
[NEW] Room names with special chars

### LINKED ISSUE #615: [NEW] Allow room names with special characters
In admin settings there is an option to "Allow special chars on room names" . The app should support this setting. We specifically need it for spaces and capital letters.

### PR DESCRIPTION
**Pull request by falcaoaugustos**
@RocketChat/ios

Closes #615

I implemented the settings parameter to allow room names with special chars.

TODO: 
- [x] Tests.

### CODE REVIEW

**Comment by rafaelks** [comment]
@falcaoaugustos Looking very good, thanks for your PR! Could you also write a few tests related to the setting and the displayName result? That would be perfect 👌

**Comment by rafaelks** [comment]
For reference, we have a similar test for this class:

https://github.com/RocketChat/Rocket.Chat.iOS/blob/6f364fd73597da672aa4aa1260f2e84c090fa6f2/Rocket.ChatTests/Models/SubscriptionSpec.swift#L121-L152

**Comment by falcaoaugustos** [comment]
Thank you, I will do it.

**Comment by rafaelks** [comment]
@falcaoaugustos Looking great! Is this ready to be merged?

**Comment by falcaoaugustos** [comment]
This is ready now. Thank you.

**Pull request merged**
