### PR TITLE
[I18N] Updated French Localization for 3.0.0 Share Extension

### PR DESCRIPTION
**Pull request by coruble**
Completely forgot I had to translate the Share Extension too...
Should have been submitted in #1918.
Checks "fr" in #1830 (for good this time)

### CODE REVIEW

**Comment by rafaelks** [comment]
Looking great! 👏

**Comment by kmav** [comment]
Bonjour  @coruble 
Pardonnez moi,  s'il vous plait. Il y a aussi le InfoPlist.strings que vous pouvez traduire  😄

**Comment by coruble** [comment]
@kmav Bonjour ! Now that the World Cup is over, sure I can translate whatever you want :-) But I don't see any InfoPlist.strings file in the repo, am I blind ?

**Comment by kmav** [comment]
Hello @coruble 
Congratulations for Mondial and France 🏅  I still remember the old classic Platini, Tigana and Giresse 😄

**Comment by kmav** [comment]
localization-resources

**Pull request merged**
