### PR TITLE
[FIX] Remove size information when uploading a file (to prevent mistakes)

### LINKED ISSUE #1075: [QUESTION] Uploaded image don't show in App
- Your Rocket.Chat app version: 1.7.4 (126)
- Your Rocket.Chat server version: 0.59.4
- Device (or Simulator) you're running with: IPhone 5s

When trying to upload a image (doesn't matter if from camera or from media library) the upload works fine. But the image doesn't show up in App. 

In WebUI (withFirefox) on the desktop computer the picture shows up, but if trying to view the image, a error is shown.

If trying to upload picture with firefox on the desktop computer everything works fine, the image shows up in app and browser.

Rocket.Chat server runs behind a nginx reverse proxy. NGinx logs following error when i try to load the image from any client.
`
2017/12/14 12:20:11 [error] 21136#21136: *30412802 upstream prematurely closed connection while sending to client, client: 10.11.13.1, server: xxx.example.com, request: "GET /file-upload/jzaNGjvqD7k8uPHH9/jakUHCacKjIliP79yxJN.jpeg HTTP/1.1", upstream: "http://10.10.1.xxx:3000/file-upload/jzaNGjvqD7k8uPHH9/jakUHCacKjIliP79yxJN.jpeg", host: "xxx.example.com", referrer: "https://xxx.example.com/direct/userXX"
`

Rocket.Chat itself doesn't log any errors neither on uplaoding nor on the request. 

Any suggestions where to look for?

### PR DESCRIPTION
**Pull request by rafaelks**
@RocketChat/ios

Closes #1075

### CODE REVIEW

**Comment by cardoso** [comment]
Just need to fix the tests before we merge :)

**Comment by mxmo0rhuhn** [comment]
This broke my ability to upload pictures. 
For every upload the message `Oops! File size is too small (min = 1) [file-too-small]` pops up.

Was really looking forward to this fix but the current situation does not help.

Server version: tested with 0.59.4 and 0.59.2

App version: Most recent from Appstore

**Comment by cardoso** [comment]
@mxmo0rhuhn Yes, I tested here and looks like this broke upload on servers below 0.60. 😞 

Any chance you can upgrade the server? We are now using a faster and more reliable upload API.

**Comment by mxmo0rhuhn** [comment]
We will setup a staging instance soon in order to test the new release for our organization. However I guess it's a major bug to not be able to fallback to the old API! After some problems with earlier releases we are not that confident when upgrading RocketChat and I'm not sure how other users handle their upgrades.

**Comment by cardoso** [comment]
Should we revert this @rafaelks?

**Comment by rafaelks** [comment]
@mxmo0rhuhn I'm really sorry for that... it really caused this weird issue in older servers. Let's revert this one @cardoso 👍

**Comment by mxmo0rhuhn** [comment]
Isn’t it a option to somehow insert a fallback to the old API version? It would be a shame if you guys did all the work with no outcome (and I’m really looking forward to the image upload fix)!

**Comment by cardoso** [comment]
We have the fallback @mxmo0rhuhn . It just seems to be broken. We'll revert this PR for the next version.

**Pull request merged**
