### PR TITLE
[NEW] Support Twitter OAuth

### LINKED ISSUE #1327: [NEW] Support Twitter OAuth

### PR DESCRIPTION
**Pull request by raghavgr**
@RocketChat/ios

Closes #1327 

Used the comments on the issue by @cardoso and the following:
https://developer.twitter.com/en/docs/basics/authentication/api-reference
https://designpieces.com/2012/12/twitter-colour-palette/
https://github.com/RocketChat/Rocket.Chat.iOS/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by rafaelks** [comment]
@raghavgr Thanks for the PR! Can you integrate the Twitter SDK (via CocoaPods) in order to authenticate the user? Ou API now supports the SDK integration, would be easier to the user to authenticate.

API: https://github.com/RocketChat/Rocket.Chat/pull/9816

**Comment by raghavgr** [comment]
@rafaelks So for the SDK, should will be using TwitterKit? https://github.com/twitter/twitter-kit-ios

I am following those instructions.

**Comment by rafaelks** [comment]
@raghavgr Yes, you're right!

**Comment by rafaelks** [comment]
@raghavgr Please, do that using CocoaPods.

**Comment by raghavgr** [comment]
I pressed Close and Comment by mistake before.

Here is my actual question:
@rafaelks 
So for the SDK, I am using the TwitterKit for iOS SDK by Twitter. 
https://github.com/twitter/twitter-kit-ios

I am following those instructions.

**Comment by raghavgr** [comment]
@rafaelks Is there a Twitter app for Rocket.Chat? I am at the part where we need to configure info.Plist,  and it requires a consumerkey from the Twitter app dashboard.
https://github.com/twitter/twitter-kit-ios/wiki/Installation#configure-infoplist

**Comment by rafaelks** [comment]
@raghavgr Ouch... I don't know why these apps do that! 👎 . Is there a way to do it dynamically?

**Comment by raghavgr** [comment]
@rafaelks For google sign-in, there seems to be a unique ID present already in info.plist. 

From what I understood from StackOverflow, .plist files are meant to be read-only and even if it were possible to dynamically change the files, the high rated answers advice not to. 
https://stackoverflow.com/questions/43433135/updating-value-in-info-plist-programmatically

There are some tutorials on how to edit them. https://ipgames.wordpress.com/tutorials/writeread-data-to-plist-file/

I have made a commit with the update to `Podfile` for `TwitterKit` to my forked repo.

**Comment by rafaelks** [comment]
@raghavgr OK... Can you create your own application (to test) and send the PR. Then we'll deal with the private keys in order to keep it private?

**Comment by raghavgr** [comment]
@rafaelks I will do that.

**Comment by rafaelks** [comment]
@raghavgr I'm really sorry about that, but we changed our minds for now regarding the SDKs: we'll remove all social SDKs and let the user authentication using OAuth only with this networks. We decided that because we're against including closed-source SDKs. So, can you please keep working into Twitter OAuth authentication using only our internal browser, like you did at first? Thank you!

**Comment by raghavgr** [comment]
@rafaelks Understood. I will update as required. 👍

**Comment by raghavgr** [comment]
@rafaelks I have updated the code such that there is no requirement for `TwitterKit` to be installed through PodFile. 

The OAuth for Twitter is complete and it is similar to other social networks. 
What kind of tests can I add?

**Comment by rafaelks** [comment]
@raghavgr Feature is not working for me... I tried using `open.rocket.chat`. Is it working for you?

**Comment by raghavgr** [comment]
Hi @cardoso 
I have made the requested changes. 👍

**Comment by rafaelks** [comment]
@raghavgr Still doesn't work for me... is it working for you?

screen shot 2018-03-05 at 06 25 57

**Comment by raghavgr** [comment]
@rafaelks
That is the same screen that I am getting. It seems I have to create an application in Twitter and pass the consumer key to authorize a login. 

Similar to this tutorial: https://code.tutsplus.com/tutorials/how-to-authenticate-users-with-twitter-oauth-20--cms-25713

**Comment by rafaelks** [comment]
@raghavgr You don't need to create a new application if your server already have one. Try making it work with `https://open.rocket.chat`.

**Comment by raghavgr** [comment]
@rafaelks 
Thanks for the feedback.
I have been working on this issue and it seems I am stuck. I understood that we don't need to create a new application as each server in Rocket.Chat will have their own credentials for api access.

However, I found that Twitter seems to be using OAuth1.0 flow to issue requests on behalf of users.
https://developer.twitter.com/en/docs/basics/authentication/overview/application-only
 
I tried to edit `OAuthManager.swift` with a OAuth1 function by following https://github.com/OAuthSwift/OAuthSwift library's twitter authorization. However it seems that a lot of things need to be modified. So I thought it would be best not to change a lot.

Since OAuth1 needs requestTokenUrl and consumerSecret, I added these fields in LoginService and LoginServiceModelMapping.

**Comment by rafaelks** [comment]
@raghavgr You're 100% right. We'll have to support OAuth1 in order to fully support Twitter, unfortunately. Do you think you can make those changes? I can see you already started. Thank you!!!

**Comment by raghavgr** [comment]
@rafaelks 
For testing, I edited OAuthManager to support only OAuth1.0 to and the screen opens up but gives me an error. 
screen shot 2018-03-09 at 6 06 12 pm
And then it is just blank with a back arrow to go back to login screen.
screen shot 2018-03-09 at 6 06 05 pm

**Comment by raghavgr** [comment]
After some debugging, I found that the request_token is not working. 
`NSErrorFailingURLKey=https://api.twitter.com/oauth/request_token,`

**Comment by cardoso** [comment]
@raghavgr I think the correct url is https://twitter.com/oauth/request_token

**Comment by raghavgr** [comment]
@cardoso I tried running with that but I still got the same error. 

Twitter developers website mentions that the request_token url is `https://api.twitter.com/oauth/request_token` https://developer.twitter.com/en/docs/basics/authentication/api-reference/request_token.

I googled the response:
`UserInfo={Response-Body={"errors":[{"code":32,"message":"Could` not authenticate you."}]}`
and found this https://github.com/J7mbo/twitter-api-php/issues/64#issuecomment-221830803.

**Comment by cardoso** [comment]
Thank you for the help @raghavgr ! I'll take it from here https://github.com/RocketChat/Rocket.Chat.iOS/pull/1586

**Pull request closed without merging**
